spring:
   datasource:
      username: basketball
      password: basketball
      url: jdbc:mysql://localhost:3306/basketball
   
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true  
      